"""empty message

Revision ID: a1ac2ab32dd0
Revises: d200a3962bb1
Create Date: 2025-11-09 22:37:59.476586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ac2ab32dd0'
down_revision = 'd200a3962bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('defaultVisibility', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('prepTime', sa.Float(), nullable=False),
    sa.Column('prepUnit', sa.String(), nullable=False),
    sa.Column('cookTime', sa.Float(), nullable=False),
    sa.Column('cookUnit', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cookbook_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_entry_unit'), ['unit'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('substitute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('ingredientEntry_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredientEntry_id'], ['ingredient_entry.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('substitute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_substitute_unit'), ['unit'], unique=False)

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_cost'))
        batch_op.drop_index(batch_op.f('ix_material_description'))
        batch_op.drop_index(batch_op.f('ix_material_quantity'))

    op.drop_table('material')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cost', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_quantity'), ['quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_cost'), ['cost'], unique=False)

    with op.batch_alter_table('substitute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_substitute_unit'))

    op.drop_table('substitute')
    op.drop_table('rating')
    op.drop_table('note')
    with op.batch_alter_table('ingredient_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_entry_unit'))

    op.drop_table('ingredient_entry')
    op.drop_table('cookbook_entry')
    op.drop_table('recipe')
    op.drop_table('user')
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_name'))

    op.drop_table('ingredient')
    # ### end Alembic commands ###
