"""empty message

Revision ID: c04d77dfdea9
Revises: 
Create Date: 2025-11-04 13:52:47.396997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04d77dfdea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('desciption', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_cost'), ['cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_name'))
        batch_op.drop_index(batch_op.f('ix_material_cost'))

    op.drop_table('material')
    # ### end Alembic commands ###
