"""empty message

Revision ID: d200a3962bb1
Revises: c04d77dfdea9
Create Date: 2025-11-09 18:44:53.074109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd200a3962bb1'
down_revision = 'c04d77dfdea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_material_name'))
        batch_op.create_index(batch_op.f('ix_material_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_quantity'), ['quantity'], unique=False)
        batch_op.drop_column('desciption')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('desciption', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_material_quantity'))
        batch_op.drop_index(batch_op.f('ix_material_description'))
        batch_op.create_index(batch_op.f('ix_material_name'), ['name'], unique=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
