"""empty message

Revision ID: d37242df39b6
Revises: a1ac2ab32dd0
Create Date: 2025-11-10 19:22:57.610265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37242df39b6'
down_revision = 'a1ac2ab32dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_entry_unit'))

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_recipe_meal'), ['meal'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_visibility'), ['visibility'], unique=False)

    with op.batch_alter_table('substitute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_substitute_unit'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_substitute_unit'), ['unit'], unique=False)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_visibility'))
        batch_op.drop_index(batch_op.f('ix_recipe_name'))
        batch_op.drop_index(batch_op.f('ix_recipe_meal'))
        batch_op.drop_column('meal')

    with op.batch_alter_table('ingredient_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_entry_unit'), ['unit'], unique=False)

    # ### end Alembic commands ###
